# Generated by Django 5.1.1 on 2024-10-02 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Ожидание'), ('completed', 'Завершён'), ('canceled', 'Отменён')], default='pending', max_length=10),
        ),
    ]
